import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Catalogo de Filmes",
  description: "Teste - Front-End",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
      return (
          <html lang="pt-BR">
            <body className="{Inter.ClassName}">
              <ReactQueryProvider>
                {children}
              </ReactQueryProvider>
            </body>
          </html>
      );    
}






























//import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

//export default function RootLayout({
//  children,
//}: Readonly<{
//  children: React.ReactNode;
//}>) {
//  return (
//    <html
//      lang="en"
//      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//    >
//      <body className="min-h-full flex flex-col">{children}</body>
//    </html>
//  );
//}
